### ISSUE TITLE
partitionArray

### ISSUE THREAD

**Issue by CMEONE** [TogaTech/helpful.js#25]
We should have a method that partitions an array based on a certain condition, like this:
```javascript
helpful.partitionArray([1, 2, 3, 4], n => n > 2) => [[3, 4], [1, 2]]
```
or:
```javascript
helpful.partitionArray([1, 2, 3, 4], n => true) => [[1, 2, 3, 4], []]
```
or:
```javascript
helpful.partitionArray([1, 2, 3, 4], n => false) => [[], [1, 2, 3, 4]]
```
The second parameter should be a function with one argument, which represents one element in the list. The return value should be a list containing two lists. The first list should contain all the values where the function parameter returns a truthy value, and the second list should contain all the values where the function parameter returns a falsey value.

The original array passed into the function should not be altered.

**Comment by carelledjuffo** [comment]
@CMEONE 
I will like to solve this issue.  Will that be possible?

**Comment by CMEONE** [comment]
@carelledjuffo Sounds great, we look forward to seeing your PR!
