### ISSUE TITLE
mergeObjects

### ISSUE THREAD

**Issue by CMEONE** [TogaTech/helpful.js#26]
We should have a method that merges two objects, like this:
```javascript
helpful.mergeObjects({"a": 1}, {"b": 2}) => {"a": 1, "b": 2}
```
or:
```javascript
helpful.mergeObjects({"a": 1, "b": 2}, {"b": 3, "c": 4}) => {"a": 1, "b": 2, "c": 4}
```
In the case where both objects contain an identical key, the first object takes precedence.

**Comment by MarcoDiazGarcia** [comment]
Hey, can you assign me to this issue, I would wanna try this.

**Comment by CMEONE** [comment]
@MarcoDiazGarcia Unfortunately, #24 already has a commit which solves this issue. However, you can feel free to try out another issue if you would like. We look forward to seeing your contribution!
